[theme]

# Primary accent for interactive elements
primaryColor = '#128c7e'

# Background color for the main content area
backgroundColor = '#dcf8c6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#25d366'

# Color used for almost all text
textColor = '#00000'
